:doctype: book
:toc:
:toc-title: Contents

[textversion]
= Sample guide and Notes

<<index.adoc#index, Click here>> to go back to the image version.

== [The Guide] How to buy a car

=== Do you need a car?

Depending on your life-style or where you live you may want to try going without one and save a lot of money.
In dense urban areas many people are starting to consider other types of mobility and sharing services. 
You can always rent for a special need like moving or a long holiday.

=== How much you want to spend?

When buying consider that the cost of acquisition is not the only the expense you'll have. 
Factor in also regular expenses such as gas, maintenance, insurance, applicable taxes and the totals costs of financing.

===  What are your needs?

How are you going to need the car in your day-ro-day life? 
Your budget plus a prioritized list of requirement helps you rationalize your buy.

* Do you usually ride alone or drive two or more people?
* How big is your family?
* Do you have small children?
* How high is safety as a requirement in your list?
* Do you drive mainly in the city?
* How many kilometers do you drive per month on average?
* What kind of extras are indispensable for you?

=== Buying New or Used?

Budget will already help define whether to buy used or new. Both have advantages and disadvantages:


*Pros and cons of buying new*

With a shiny new car, you are getting those nice new features that bring added that safety, comfort and convenience you may seek.

But that costs more and as soon as you drive that car off the stand it will immediately be worth at least 10% less.

A new car removes the uncertainty a car with an unknown history raises. 
Although a new car can always be defective you have some consumer protection.

Usually there will more and better options for financing a new car.

When buying insurance, while a new car won't get those penalization points older cars receive when factoring in risks, it will have higher
market value and you will also be more inclined to chose policies more inclusive in damage coverage as you feel you have more value to lose.

*Pros and cons of buying used*

Buying a car second-hand lowers the price dramatically but used cars usually need to be maintained more often. If the make and model of
 your car is common, parts are cheaper and easier to obtain. Less common cars or from a maker that ships lots of different models every 
year, might be heavy on the wallet and a headache to maintain.

When you buy a used car from a private seller, you don't necessarily have any information on how it was kept or if got into any serious 
accidents. There are some dealerships that offer warranty on used cars but they are usually short.

The insurance for a common used make/model might be lower depending on its, by now, well-known risk stats but you might feel inclined to
 include more coverage in terms of assistance.

*4. How to finance it*

Most common options are direct financing, dealership financing or leasing. Decide taking into account how much you value owning the car 
straight off the bat and what kind of collaterals you have or want to offer.


*Direct financing*

In this option, the bank is just lending you money and the car you buy is registered in your name.

Bank loans usually have higher rates, especially for used cars. If you offer a savings account as collateral, you may get lower rates.
Ask your bank and a few others for a car loan simulation. Understand the usual credit terms and compare the terms offered in the 
simulations you got.

*Dealership financing*

Some dealerships offer financing. This means you are doing two things, buying a car and contracting a loan where you agree to pay, 
over a period, the amount financed plus a finance charge. Be sure to understand if the price of the car with financing charges still
interests you.

The dealer typically offers this contract in partnership with a financial institution which will collect the payments.

Dealers may also have trade-in programs where you can get a discount by giving your current car or have special manufacturer-sponsored sale,
 but they might be limited to a certain car different from the one you want, require a larger down payment or a shorter length for the 
contract.

*Leasing*

With this modality you pay a monthly fee to lease the car and do not own it. Depending on your contracted modality, by the end of the lease
 you may be obliged or be given the option of buying the car. The car is bought by paying the contractually agreed amount
 (usually called the residual value) and property is transferred over to you.

Leasing offers better rates but have more terms than a regular car loan. Usually you have to consider terms such as down payment, rate
, milleage allowance, length of contract, financing charge and amount of last payment in the event your want to buy the car.


===  Where to buy it? 

*Used:*

* Ask around, maybe someone in your network knows of someone that owns a car they don't use much and have decided to sell.
* Consider buying from someone with which you already have some degree of trust or a car for which you already have some history information.
* Company informal market places or a dealer that provides warranty.

You can get a better deal from open online market places like muuv or stand virtual. Be sure to select a platform that offers some
 guarantees like a certified warranty and a test-drive as part of the process. 
If allowed, take it the to a car shop you trust for a quick check and an overview report. 

Always pay the car only against delivery.

*New:*

You have the physical stands of the brand, but most brands also have their online shop and are present in other dedicated online platforms
 such as muuv.pt.

Are you a member of ACP, DECO or similar association's? Then you might want to check if they have special deals on cars that interest you.


'''

include::how.adoc[]

